In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

List of things to review
- QQ Plot
- SNS hist, paired with QQ plot
- List comprehension
- Lambdas
- Dictionary comprehension

In [2]:
# import tables

# medication doses
df1 = pd.read_csv('/Users/danherman/Desktop/oud_treatment_outcome/data/clean_data/eda_data/medication.csv')

# urine drug screen
df2 = pd.read_csv('/Users/danherman/Desktop/oud_treatment_outcome/data/clean_data/eda_data/urine_drug_screen.csv')

# self reported use
df3 = pd.read_csv('/Users/danherman/Desktop/oud_treatment_outcome/data/clean_data/eda_data/self_reported_use.csv')

# target
target = pd.read_csv('/Users/danherman/Desktop/oud_treatment_outcome/data/clean_data/eda_data/target.csv')

In [3]:
df1.shape, df2.shape, df3.shape, target.shape

((1246, 7), (1917, 11), (1668, 13), (1917, 2))

In [4]:
import functools as ft

dfs = [df1, df2, df3, target]

df = ft.reduce(lambda left, right: pd.merge(left, right, on='patdeid', how='left'),dfs)

In [5]:
df.drop(columns='Unnamed: 0', inplace=True)

In [6]:
df[:5]

,patdeid,medication,total_dose,total_visits,total_dose_visit,metha_dose_visit,bupe_dose_visit,t_Amphetamines,t_Benzodiazapines,t_Methadone,...,sru_cocaine,sru_amphetamine,sru_methamphetamine,sru_opiates,sru_benzodiazepines,sru_propoxyphene,sru_methadone,sru_oxycodone,sru_other,outcome
0,1,2.0,5188.0,24,216.17,0.00,216.17,2.0,0.0,0.0,...,0.0,0.0,2.0,30.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,2.0,1940.0,24,80.83,0.00,80.83,0.0,0.0,0.0,...,2.0,0.0,0.0,64.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,1.0,13035.0,24,543.12,543.12,0.00,1.0,4.0,25.0,...,54.0,0.0,1.0,220.0,8.0,0.0,0.0,0.0,0.0,0.0
3,4,2.0,5304.0,24,221.00,0.00,221.00,0.0,9.0,0.0,...,14.0,0.0,0.0,81.0,14.0,0.0,0.0,1.0,0.0,0.0
4,6,2.0,32.0,2,16.00,0.00,16.00,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,25.0,0.0,0.0